### ISSUE TITLE
Fails to compile on RN 0.47+

### ISSUE THREAD

**Issue by brwelch** [dgladkov/react-native-image-rotate#7]
/react-native-image-rotate/android/src/main/java/io/codebakery/imagerotate/ImageRotatePackage.java:21: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-image-rotate:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-rotate:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by allthetime** [comment]
For anyone struggling with this I managed to fix it by getting rid of the line quoted in the error message 

`@override`

at

`/react-native-image-rotate/android/src/main/java/io/codebakery/imagerotate/ImageRotatePackage.java:21`

**Comment by dgladkov** [comment]
I'm not working with RN anymore, but I'll gladly accept PR for this if you can verify it works on latest RN Android
